name: Unzip Albion.zip

# Este flujo de trabajo se ejecuta cuando se hace un 'push' (subida)
# que incluye el archivo 'albion.zip'
on:
  push:
    paths:
      - 'albion.zip'

jobs:
  unzip:
    # Se ejecutará en un servidor virtual de Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en el servidor virtual
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Descomprime el archivo y luego lo elimina
      - name: Unzip albion.zip
        run: |
          unzip -o albion.zip -d ./
          rm albion.zip

      # 3. Guarda los archivos extraídos en tu repositorio
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Descomprimido albion.zip'
          branch: main # Asegúrate de que esta es tu rama principal (puede ser 'master')
